feat(filenode): split store on files and simple test

diff --git a/.github/workflows/commit.yml b/.github/workflows/commit.yml
--- a/.github/workflows/commit.yml
+++ b/.github/workflows/commit.yml
@@ -15,7 +15,7 @@ jobs:
       - uses: actions/checkout@v4
       - uses: actions/setup-go@v5
         with:
-          go-version: "1.23.5"
+          go-version: "1.24.0"
 
       - run: go mod verify
 
@@ -34,7 +34,7 @@ jobs:
 
       - uses: actions/setup-go@v5
         with:
-          go-version: "1.23.5"
+          go-version: "1.24.0"
 
       - name: Set up QEMU for cross-compilation of Docker images
         uses: docker/setup-qemu-action@v3
@@ -43,6 +43,16 @@ jobs:
         uses: docker/setup-buildx-action@v3
 
       - run: go mod download
+
+      - run: go generate ./...
+
+      - name: Check for modified files
+        run: |
+          if ! git diff --quiet; then
+            echo "Error: Running 'go generate' modified files. Please commit these changes:"
+            git diff
+            exit 1
+          fi
 
       - name: Run GoReleaser
         uses: goreleaser/goreleaser-action@v6
